"""
scripts/seed_us_channels.py — Seed 10 US test channels into channel_info.db
"""

import sys
import os
from datetime import datetime, timezone

# Ensure project root is in sys.path
_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from database.channel_repository import upsert_channel
from services.attraction_score import compute_cas, cas_tier

US_CHANNELS = [
    {
        "platform": "youtube",
        "channel_id": "UCBJycsmduvYEL83R_U4JcqQ",
        "channel_url": "https://youtube.com/channel/UCBJycsmduvYEL83R_U4JcqQ",
        "username": "@mkbhd",
        "channel_name": "Marques Brownlee (MKBHD)",
        "follower_count": 18500000,
        "broadcast_freq_weekly": 2.5,
        "last_live_at": "2026-08-20T18:00:00Z",
        "avg_viewers": 120000,
        "total_livestreams": 45,
        "category": "Technology",
        "language": "en",
        "description": "Quality tech videos | Consumer electronics, AI gadgets, smartphone reviews & tech podcasts.",
        "is_verified": True,
        "location_raw": "New York, US",
        "country": "US",
        "region_tag": "US-NYC",
        "seller_info": {"is_seller": True, "brand_name": "MKBHD", "social_links": ["https://twitter.com/mkbhd"]},
    },
    {
        "platform": "youtube",
        "channel_id": "UCcefcZRL2sSR70URRy64Z0g",
        "channel_url": "https://youtube.com/channel/UCcefcZRL2sSR70URRy64Z0g",
        "username": "@ycombinator",
        "channel_name": "Y Combinator",
        "follower_count": 1200000,
        "broadcast_freq_weekly": 3.0,
        "last_live_at": "2026-08-22T19:00:00Z",
        "avg_viewers": 45000,
        "total_livestreams": 80,
        "category": "Business & Startups",
        "language": "en",
        "description": "Startup advice, founder interviews, tech trends, and Demo Day streams from Y Combinator.",
        "is_verified": True,
        "location_raw": "San Francisco, CA, USA",
        "country": "US",
        "region_tag": "US-SFO",
        "seller_info": {"is_seller": True, "brand_name": "Y Combinator", "social_links": ["https://ycombinator.com"]},
    },
    {
        "platform": "tiktok",
        "channel_id": "tiktok_garyvee",
        "channel_url": "https://www.tiktok.com/@garyvee",
        "username": "@garyvee",
        "channel_name": "Gary Vaynerchuk (GaryVee)",
        "follower_count": 15400000,
        "broadcast_freq_weekly": 4.0,
        "last_live_at": "2026-08-21T15:30:00Z",
        "avg_viewers": 25000,
        "total_livestreams": 110,
        "category": "Marketing & Business",
        "language": "en",
        "description": "CEO of VaynerMedia | Entrepreneur, Investor, Speaker | Marketing, NFT & Social Media strategy.",
        "is_verified": True,
        "location_raw": "New York, NY",
        "country": "US",
        "region_tag": "US-NYC",
        "seller_info": {"is_seller": True, "brand_name": "VaynerMedia", "social_links": ["https://garyvaynerchuk.com"]},
    },
    {
        "platform": "youtube",
        "channel_id": "UCSHZKyawb77ixDdsGog4iWA",
        "channel_url": "https://youtube.com/channel/UCSHZKyawb77ixDdsGog4iWA",
        "username": "@lexfridman",
        "channel_name": "Lex Fridman",
        "follower_count": 4200000,
        "broadcast_freq_weekly": 1.5,
        "last_live_at": "2026-08-19T20:00:00Z",
        "avg_viewers": 85000,
        "total_livestreams": 35,
        "category": "AI & Robotics",
        "language": "en",
        "description": "Conversations about AI, science, technology, history, philosophy, and consciousness.",
        "is_verified": True,
        "location_raw": "San Francisco, CA",
        "country": "US",
        "region_tag": "US-SFO",
        "seller_info": {"is_seller": False, "brand_name": "Lex Fridman Podcast"},
    },
    {
        "platform": "web",
        "channel_id": "techcrunch_com",
        "channel_url": "https://techcrunch.com",
        "username": "techcrunch.com",
        "channel_name": "TechCrunch",
        "follower_count": 2800000,
        "broadcast_freq_weekly": 5.0,
        "last_live_at": "2026-08-23T10:00:00Z",
        "avg_viewers": 15000,
        "total_livestreams": 60,
        "category": "Tech News",
        "language": "en",
        "description": "Reporting on the business of technology, startups, venture capital funding, and Silicon Valley live events.",
        "is_verified": True,
        "location_raw": "San Francisco, CA",
        "country": "US",
        "region_tag": "US-SFO",
        "seller_info": {"is_seller": True, "brand_name": "TechCrunch Disrupt"},
    },
    {
        "platform": "youtube",
        "channel_id": "UCESLZhusAkFfsNsApnjF_Cg",
        "channel_url": "https://youtube.com/channel/UCESLZhusAkFfsNsApnjF_Cg",
        "username": "@allin",
        "channel_name": "All-In Podcast",
        "follower_count": 650000,
        "broadcast_freq_weekly": 1.0,
        "last_live_at": "2026-08-22T21:00:00Z",
        "avg_viewers": 95000,
        "total_livestreams": 50,
        "category": "Venture Capital & Finance",
        "language": "en",
        "description": "Chamath Palihapitiya, Jason Calacanis, David Sacks & David Friedberg cover economics, tech, and startups.",
        "is_verified": True,
        "location_raw": "San Francisco, CA",
        "country": "US",
        "region_tag": "US-SFO",
        "seller_info": {"is_seller": True, "brand_name": "All-In Summit"},
    },
    {
        "platform": "tiktok",
        "channel_id": "tiktok_alexhormozi",
        "channel_url": "https://www.tiktok.com/@alexhormozi",
        "username": "@alexhormozi",
        "channel_name": "Alex Hormozi",
        "follower_count": 2300000,
        "broadcast_freq_weekly": 3.5,
        "last_live_at": "2026-08-20T17:00:00Z",
        "avg_viewers": 18000,
        "total_livestreams": 40,
        "category": "Business & Sales",
        "language": "en",
        "description": "Founder of Acquisition.com | Scaling $100M+ businesses | Author of $100M Offers & $100M Leads.",
        "is_verified": True,
        "location_raw": "Los Angeles, CA",
        "country": "US",
        "region_tag": "US-LAX",
        "seller_info": {"is_seller": True, "brand_name": "Acquisition.com"},
    },
    {
        "platform": "web",
        "channel_id": "wired_com",
        "channel_url": "https://wired.com",
        "username": "wired.com",
        "channel_name": "WIRED Magazine",
        "follower_count": 3500000,
        "broadcast_freq_weekly": 2.0,
        "last_live_at": "2026-08-21T14:00:00Z",
        "avg_viewers": 22000,
        "total_livestreams": 25,
        "category": "Science & Technology",
        "language": "en",
        "description": "WIRED is the essential source of information and ideas that make sense of a world in constant transformation.",
        "is_verified": True,
        "location_raw": "San Francisco, CA",
        "country": "US",
        "region_tag": "US-SFO",
        "seller_info": {"is_seller": True, "brand_name": "WIRED"},
    },
    {
        "platform": "youtube",
        "channel_id": "UCgcgQ593Vv75Jsq44dJ7zkw",
        "channel_url": "https://youtube.com/channel/UCgcgQ593Vv75Jsq44dJ7zkw",
        "username": "@saradietschy",
        "channel_name": "Sara Dietschy",
        "follower_count": 920000,
        "broadcast_freq_weekly": 2.0,
        "last_live_at": "2026-08-18T16:00:00Z",
        "avg_viewers": 35000,
        "total_livestreams": 30,
        "category": "Tech & Lifestyle",
        "language": "en",
        "description": "Tech reviews, creative entrepreneurship vlogs, and That Creative Life podcast streams.",
        "is_verified": True,
        "location_raw": "Los Angeles, CA",
        "country": "US",
        "region_tag": "US-LAX",
        "seller_info": {"is_seller": True, "brand_name": "That Creative Life"},
    },
    {
        "platform": "web",
        "channel_id": "producthunt_com",
        "channel_url": "https://producthunt.com",
        "username": "producthunt.com",
        "channel_name": "Product Hunt",
        "follower_count": 1800000,
        "broadcast_freq_weekly": 7.0,
        "last_live_at": "2026-08-23T12:00:00Z",
        "avg_viewers": 50000,
        "total_livestreams": 150,
        "category": "SaaS & Product Launch",
        "language": "en",
        "description": "The best new products in tech. Discover, launch, and live stream SaaS apps and AI tools every day.",
        "is_verified": True,
        "location_raw": "San Francisco, CA",
        "country": "US",
        "region_tag": "US-SFO",
        "seller_info": {"is_seller": True, "brand_name": "Product Hunt"},
    },
]

def seed():
    count = 0
    now_dt = datetime.now(timezone.utc)
    for ch in US_CHANNELS:
        ch["cas"] = compute_cas(ch)
        ch["cas_computed_at"] = now_dt
        ch["tier"] = cas_tier(ch["cas"])
        if upsert_channel(ch):
            count += 1
            print(f"[OK] [US] {ch['channel_name']} (Platform={ch['platform']}, CAS={ch['cas']}) saved!")
        else:
            print(f"[FAIL] [US] {ch['channel_name']} failed!")
    print(f"\nSUCCESS: Seeded {count}/{len(US_CHANNELS)} US test channels into channel_info.db successfully!")

if __name__ == "__main__":
    seed()
